version: '2'
services:
  antidote1:
    image: antidotedb/antidote:local
    environment:
      NODE_NAME: "antidote@antidote1"
      SHORT_NAME: "true"
    ports:
      - "8087:8087"
  antidote2:
    image: antidotedb/antidote:local
    environment:
      NODE_NAME: "antidote@antidote2"
      SHORT_NAME: "true"
    ports:
      - "8088:8087"
  antidote3:
    image: antidotedb/antidote:local
    environment:
      NODE_NAME: "antidote@antidote3"
      SHORT_NAME: "true"
    ports:
      - "8089:8087"
  antidote4:
    image: antidotedb/antidote:local
    environment:
      NODE_NAME: "antidote@antidote4"
      SHORT_NAME: "true"
    ports:
      - "8090:8087"
  link:
    image: erlang:19
    volumes:
      - .:/code
    command: '/code/link.sh'
    depends_on:
      - antidote1
      - antidote2
      - antidote3
      - antidote4
  cadvisor:
    image: google/cadvisor:latest
    stdin_open: true
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    tty: true
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ".:/data"
    command: "--config.file=/data/prometheus.yml"
    depends_on:
      - link
      - cadvisor
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./provisioning:/etc/grafana/provisioning"
      - "./dashboards:/var/lib/grafana/dashboards/provisioning"
    depends_on:
      - prometheus
