{
 "title": "Node Network Traffic",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"antidote1\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_received"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"antidote1\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_transmitted"
    }
   ]
  },
  {
   "title": "Node2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"antidote2\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_received"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"antidote2\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_transmitted"
    }
   ]
  },
  {
   "title": "Node3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"antidote3\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_received"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"antidote3\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_transmitted"
    }
   ]
  },
  {
   "title": "Node4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"antidote4\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_received"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"antidote4\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_transmitted"
    }
   ]
  }
 ]
}