{
 "title": "Node Network Traffic",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"antidote1\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_received"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"antidote1\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_transmitted"
    }
   ]
  },
  {
   "title": "Node2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"antidote2\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_received"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"antidote2\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_transmitted"
    }
   ]
  },
  {
   "title": "Node3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"antidote3\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_received"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"antidote3\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_transmitted"
    }
   ]
  },
  {
   "title": "Node4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"antidote4\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_received"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"antidote4\", interface=\"eth0\"}[1m])",
     "legendFormat": "bytes_transmitted"
    }
   ]
  },
  {
   "title": "dc1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(antidote_inter_dc_receive_total{instance=\"antidote1:3001\"}[1m])",
     "legendFormat": "receive"
    },
    {
     "expr": "irate(antidote_inter_dc_transmit_total{instance=\"antidote1:3001\"}[1m])",
     "legendFormat": "transmit"
    },
    {
     "expr": "irate(antidote_handle_call_bytes_total{instance=\"antidote1:3001\"}[1m])",
     "legendFormat": "handle"
    }
   ]
  },
  {
   "title": "dc2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(antidote_inter_dc_receive_total{instance=\"antidote2:3001\"}[1m])",
     "legendFormat": "receive"
    },
    {
     "expr": "irate(antidote_inter_dc_transmit_total{instance=\"antidote2:3001\"}[1m])",
     "legendFormat": "transmit"
    },
    {
     "expr": "irate(antidote_handle_call_bytes_total{instance=\"antidote2:3001\"}[1m])",
     "legendFormat": "handle"
    }
   ]
  },
  {
   "title": "Pb Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(antidote_pb_response_total{instance=\"antidote1:3001\"}[1m])",
     "legendFormat": "pb response"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{image=\"uc-test\"}[30s])",
     "legendFormat": "container in"
    }
   ]
  },
  {
   "title": "Pb In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(antidote_pb_receive_total{instance=\"antidote1:3001\"}[1m])",
     "legendFormat": "pb receive"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{image=\"uc-test\"}[30s])",
     "legendFormat": "container out"
    }
   ]
  }
 ]
}